services:
  redis:
    image: "redis:alpine" # 使用官方Redis映像
    container_name: redis_service
    ports:
      - "6379:6379" # 將Redis的默認端口映射到宿主機
    restart: always

  flask:
    build: . # Flask應用的Dockerfile
    container_name: flask_service
    ports:
      - "8000:8000" # 將Flask的設置端口映射到宿主機
    tty:
      true
    depends_on:
      - redis # Flask服務依賴於Redis
